CREATE DATABASE shopping_website;
USE shopping_website;
CREATE TABLE users (     id INT AUTO_INCREMENT PRIMARY KEY,     username VARCHAR(255) NOT NULL,     password VARCHAR(255) NOT NULL,     email VARCHAR(255),     registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     status ENUM('active', 'inactive') DEFAULT 'active' );
CREATE TABLE categories (     id INT AUTO_INCREMENT PRIMARY KEY,     name VARCHAR(255) NOT NULL );
CREATE TABLE products (     id INT AUTO_INCREMENT PRIMARY KEY,     name VARCHAR(255) NOT NULL,     description TEXT,     price DECIMAL(10, 2) NOT NULL,     stock INT NOT NULL,     category_id INT,     FOREIGN KEY (category_id) REFERENCES categories(id) );
CREATE TABLE cart (     id INT AUTO_INCREMENT PRIMARY KEY,     user_id INT,     product_id INT,     quantity INT NOT NULL,     FOREIGN KEY (user_id) REFERENCES users(id),     FOREIGN KEY (product_id) REFERENCES products(id) );
CREATE TABLE orders (     id INT AUTO_INCREMENT PRIMARY KEY,     user_id INT,     total_price DECIMAL(10, 2) NOT NULL,     status ENUM('pending', 'paid', 'shipped', 'delivered') DEFAULT 'pending',     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,     FOREIGN KEY (user_id) REFERENCES users(id) );
CREATE TABLE order_items (     id INT AUTO_INCREMENT PRIMARY KEY,     order_id INT,     product_id INT,     quantity INT NOT NULL,     price DECIMAL(10, 2) NOT NULL,     FOREIGN KEY (order_id) REFERENCES orders(id),     FOREIGN KEY (product_id) REFERENCES products(id) );
CREATE TABLE logs (     id INT AUTO_INCREMENT PRIMARY KEY,     user_id INT,     product_id INT,     action ENUM('view', 'buy') NOT NULL,     timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     FOREIGN KEY (user_id) REFERENCES users(id),     FOREIGN KEY (product_id) REFERENCES products(id) );
ALTER TABLE users ADD COLUMN role ENUM('admin', 'customer') DEFAULT 'customer' AFTER email;
ALTER TABLE products ADD COLUMN image_url VARCHAR(255) AFTER description, ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER stock;
ALTER TABLE orders ADD COLUMN payment_method ENUM('credit_card', 'paypal', 'cash_on_delivery') DEFAULT 'credit_card' AFTER total_price, ADD COLUMN shipping_address VARCHAR(255) AFTER payment_method;
ALTER TABLE cart ADD COLUMN status ENUM('active', 'submitted', 'abandoned') DEFAULT 'active' AFTER quantity;
ALTER TABLE logs ADD COLUMN is_payment_successful BOOLEAN DEFAULT FALSE AFTER action;
ALTER TABLE categories ADD COLUMN parent_id INT DEFAULT NULL AFTER name, ADD FOREIGN KEY (parent_id) REFERENCES categories(id);
CREATE TABLE shipment (     id INT AUTO_INCREMENT PRIMARY KEY,     order_id INT,     shipped_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     shipping_status ENUM('pending', 'shipped', 'delivered') DEFAULT 'pending',     tracking_number VARCHAR(255),     FOREIGN KEY (order_id) REFERENCES orders(id) );
INSERT INTO categories (name)values('cat');
INSERT INTO products (name,description,price,stock,category_id)values('橘猫','这是一只橘猫，大橘为重，价值千金。','999','1','1');
UPDATE products SET image_url = '1.jpg' WHERE id = 1;
ALTER TABLE categories DROP CONSTRAINT `categories_ibfk_1`;
ALTER TABLE categories DROP COLUMN parent_id;
INSERT INTO categories (name)values('friut');
INSERT INTO products (name,description,price,stock,category_id)values('橘子','果肉酸甜，可加工制成果汁、果酱、果糕等食品。','6','100','2');
UPDATE products SET image_url = '2.jpg' WHERE id = 2;
INSERT INTO users (username, password, email, status, role) VALUES ('admin','111111','13360804995@163.com','active','admin');
